### DISCUSSION TITLE
Discussion about player tag (nametag) plugins

### DISCUSSION THREAD

**Discussion by MATRIX-feather** [XiaMoZhiShi/MorphPlugin#38] [General]
Here you can talk various things about player tag plugins, from compatibility, to configuration, or something else.

Currently known plugins:
- [TAB](https://modrinth.com/plugin/tab-was-taken): The original player tag hides when someone disguises as a mob, if disguised as another player, it will show the target's name, along with its style if they are online.

- [UnlimitedNameTags](https://github.com/alexdev03/UnlimitedNametags): It works, tag is always visible no matter disguising or not, *additional configuration is required if you wish to achieve some effect (Hide nametag when disguised as a mob, or display disguise's nickname when disguised as a player)*
  - *Upon disguise/undisguise, there will be two tags within a short time, it may related to how they implement the feature*
  - Displaying other player's style is not possible currently, not supported either by FeatherMorph and UNT, only displaying name is supported via `%feathermorph_state_name%`

**Comment by MATRIX-feather** [comment]
For reference, if someone wants to achieve the *effect* mentioned above with UNT, here's what our server was doing:

``````YAML
nameTags:
  default:
    permission: nametag.default
    linesGroups:
    - lines:
      - ' %vault_prefix%%player_name%%vault_suffix% ' # Player's Original name, if not disguised
      modifiers:
      - type: conditional
        parameter: '%feathermorph_state_status%' # The Condition
        condition: ==
        value: 'false'

    - lines:
      - '' # Hide tag, if disguised as mob
      modifiers:
      - type: conditional
        parameter: '%feathermorph_state_status%' # Player disguised?
        condition: ==
        value: 'true'
      - type: conditional
        parameter: '%feathermorph_state_provider_is?minecraft%' # If provider namespace is "minecraft", which is used by the Vanilla Disguise Provider
        condition: ==
        value: 'true'

    - lines:
      - ' %feathermorph_state_name% '  # Fake name if disguised as player
      modifiers:
      - type: conditional
        parameter: '%feathermorph_state_status%'  # Disguised?
        condition: ==
        value: 'true'
      - type: conditional
        parameter: '%feathermorph_state_provider_is?player%'  # If provider namespace is "player", which is used by the Player Disguise Provider
        condition: ==
        value: 'true'
``````
